const SET_MESSAGES = "SET_MESSAGES";
const SET_THREAD_LISTING = "SET_THREAD_LISTING";
const SET_SINGLE_MESSAGE = 'SET_SINGLE_MESSAGE';
const SET_USER_DATA = 'SET_USER_DATA';
const SET_VISITOR_LOADING = 'SET_VISITOR_LOADING';
const SET_AGENT_LOADING = 'SET_AGENT_LOADING';
export {
    SET_MESSAGES,
    SET_THREAD_LISTING,
    SET_SINGLE_MESSAGE,
    SET_USER_DATA,
    SET_AGENT_LOADING,
    SET_VISITOR_LOADING
}
